### ISSUE TITLE
osrmRoute function returns an error:  Error: parse error: premature EOF

### ISSUE THREAD

**Issue by kintero** [rCarto/osrm#10]
Hello,

I'm trying to use osrmRoute, but it returned me an error with this messages:  "Error: parse error: premature EOF".  And I don't know what  happens. It even happens with documentation's example. 

I'm using version 3.0.0 from CRAN.

Thanks.

**Comment by rCarto** [comment]
Are other functions working? If not, it could be an OSRM server temporary stop. I am afk till monday 18, I can't do much till then, sorry.

**Comment by rCarto** [comment]
osrmRoute works fine for me. Can you send me a sample of your data?

**Comment by rCarto** [comment]
See #12
