### ISSUE TITLE
Problem with self-hosted server connection

### ISSUE THREAD

**Issue by asitemade4u** [rCarto/osrm#123]
Hi,
I have issues executing `osrm::osrmNearest` with my self-hosted OSRM server.

Here are the details:

1. I self host an OSRM server using docker.
- I just changed the port to `5111` as it was colliding with another of my self-hosted servers.
Nevertheless, it works fine and responds to a `curl` to its local IP address (`192.168.1.16:5111`) such as:

```bash
curl "192.168.1.16:5111/route/v1/foot/40.6476940,-73.9803640;40.6551440,-74.0035490?steps=true"
```
I assume the OSRM API responds well then.
- I also did not turn on the GUI of the OSRM server in my `docker-compose.yml` file.

2. I installed the `osrm` plugin in R. My R installation is also served by a self-hosted server using CodeServer -- and works just fine.
3. I followed your instructions on how to connect the plugin with the server (notably the trailing `/`).
4. I executed the above `curl` instruction from the `bash` terminal of my R coding environment and it returned a correct result. So I assume I can connect to the API from my development environment, from where the below code is executed.
5. The R code I am using is straightforward:

- I define the server and the profile:
```R
options(osrm.server = "192.168.1.16:5111/")
options(osrm.profile = "foot")
```
- I load trackpoint coordinates (lat/lon) from a Postgis database, among other relevant data columns, into a dataframe, `thetmp`
- I transform `thetmp` into a `sf` geometry using `sf::st_as_sf`: the column `thetmp$geometry` replaces the two coordinate columns, as a result.
- Lastly, I loop all the rows of `thetmp` dataframe and add nearest coordinates of each trackpoint into a new column to the dataframe, `thetmp$new`:

```bash
thetmp$new[i] <- osrm::osrmNearest(loc = thetmp$geometry[i], osrm.server = getOption("osrm.server"), osrm.profile = getOption("osrm.profile")
```

- I get no error while executing but the outcome of each cell in the `new` dataframe column is always the same, and obviously not what I was expecting: 

```R
[[1]]
[1] "loc"
```

What am I doing wrong?

S.

PS1. I also tried to prefix the server address with `http://` but it yields the same result.
PS2. Nous pouvons communiquer en Français si cela est plus facile pour vous, car je suis un compatriote vivant aux US. ;o))

**Comment by rCarto** [comment]
Hello, I'm AFK right now, I'll have a look at it in early September. 
Do the other function works (e.g. osrmRoute() or osrmTable())?

**Comment by rCarto** [comment]
Ok thanks, 
Does this snippet work ?

```r
library(osrm)
osrmRoute(src = c(-73.9803640, 40.6476940), dst = c(-74.0035490, 40.6551440), 
          osrm.server = "http://192.168.1.16:5111/", 
          osrm.profile = "foot")
```

**Comment by rCarto** [comment]
> That said, when I input `http://192.168.1.16:5111/` in my browser, I get this error message from OSRM:
> 
> ```shell
> {"message":"URL string malformed close to position 1: \"\/\"","code":"InvalidUrl"}
> ```

This message is returned by OSRM, so it's OK. OSRM is published and accessible at this address...

Anyway the problem does not seem to be linked specifically to `osrmNearest()`. I'll change the label of the issue.

**Comment by floswald** [comment]
hey there,
i have exactly the same problem. when I run your example I get

```
> travel_time$durations[1:5,1:5]
  1 2 3 4 5
1 0 0 0 0 0
2 0 0 0 0 0
3 0 0 0 0 0
4 0 0 0 0 0
5 0 0 0 0 0
```

each time. what's weird is this:

```
> travel_time$source[1:5,]
       lon      lat
1 0.337306 51.54285
2 0.337306 51.54285
3 0.337306 51.54285
4 0.337306 51.54285
5 0.337306 51.54285
> travel_time$destinations[1:5,]
       lon      lat
1 0.337306 51.54285
2 0.337306 51.54285
3 0.337306 51.54285
4 0.337306 51.54285
5 0.337306 51.54285
```

when in reality those should be (when I use the online routing server)

```
> travel_time$sources
         lon      lat
1   13.43857 52.47726
2   13.57897 52.45815
3   13.49047 52.61726
4   13.51960 52.49760
5   13.45592 52.50109
6   13.33849 52.49470
```

**Comment by floswald** [comment]
oh no, just realised that the API is returning zero distance all the time! so that's the problem here...

**Comment by floswald** [comment]
nevermind, I reconfigured the package in a new location and on a new openstreetmap, now it works. strangely only the R package works, the curl calls always return zero distance...

**Comment by rCarto** [comment]
Hi @asitemade4u , 
Have you solved the problem?
