### ISSUE TITLE
Travel time equals zero using osrmTable() in R

### ISSUE THREAD

**Issue by tian-y** [rCarto/osrm#14]
Hello, I try to use the osrm package in R to get the travel time matrix. I tried with both my own dataset and the example in README. Both time I got a travel time matrix (duration) equal zero
`data("com")

distCom <- osrmTable(loc = com[1:50, c("comm_id","lon","lat")])
distCom$durations[1:5,1:5]
             FR3162292119 FR3162212035 BE241011 BE241024 FR3162270520
FR3162292119            0            0        0        0            0
FR3162212035            0            0        0        0            0
BE241011                0            0        0        0            0
BE241024                0            0        0        0            0
FR3162270520            0            0        0        0            0`

Then I check distcom$destinations and distcom$sources, found they all have the same coordination.

` distCom$destinations[1:5,]
                   lon      lat
FR3162292119 -114.1306 34.27882
FR3162212035 -114.1306 34.27882
BE241011     -114.1306 34.27882
BE241024     -114.1306 34.27882
FR3162270520 -114.1306 34.27882
distCom$sources[1:5,]
                   lon      lat
FR3162292119 -114.1306 34.27882
FR3162212035 -114.1306 34.27882
BE241011     -114.1306 34.27882

BE241024     -114.1306 34.27882

FR3162270520 -114.1306 34.27882
com[1:5,]
       comm_id        name      lon      lat
1 FR3162292119     Bethune 2.647810 50.51990
2 FR3162212035     Annezin 2.619300 50.54150
3     BE241011 Denderleeuw 4.071241 50.88721
4     BE241024    Haaltert 4.005772 50.90225
5 FR3162270520       Locon 2.666170 50.57050`

can you please tell me what went wrong?

**Comment by rCarto** [comment]
Yes, I can! The public osrm server is currently running on a California dataset instead of the world dataset. It should be fixed un the following days. See https://github.com/Project-OSRM/osrm-backend/issues/3186
