### ISSUE TITLE
Are there any way to get a bulk of distances?

### ISSUE THREAD

**Issue by tian-y** [rCarto/osrm#16]
Hello, I am a happy user of osrm's R package. 
I am trying to get a matrix of distances and a matrix of durations between 4000 points.
The matrix of duration is easy to get. I can use the osrmTable function to get the duration of multiple start points and multiple destinations. 
However, for the distance, I can only get one value of distance between two points every execution of osrmRoute() function. It will take weeks for me to get the entire matrix.
Could you please tell me if there's a better way to get the matrix of distances?

**Comment by rCarto** [comment]
Short answer: no.
The OSRM API does not allow to query distances matrices. However, if you can run your own OSRM instance, you can have a look at this issue: https://github.com/Project-OSRM/osrm-backend/issues/1353
