### ISSUE TITLE
Routing with my points

### ISSUE THREAD

**Issue by Robinlovelace** [rCarto/osrm#17]
Just trying this out and getting an error:

```r
origin = tmap::geocode_OSM("Bradford")
destination = tmap::geocode_OSM("Leeds")
ro = osrmRoute(origin, destination)
```
```
osrmRoute function returns an error: 
Error: URL string malformed close to position 31: "73, 51"
```

Any ideas?

**Comment by Robinlovelace** [comment]
Update: was an issue of not providing the right data class I think - this fixed it:

```r
origin = tmap::geocode_OSM("Bradford")
destination = tmap::geocode_OSM("Leeds")
o = SpatialPointsDataFrame(matrix(origin$coords, ncol = 2), proj4string = CRS("+init=epsg:4326"),
                           data.frame(name = "o"))
d = SpatialPointsDataFrame(matrix(destination$coords, ncol = 2), proj4string = CRS("+init=epsg:4326"),
                           data.frame(name = "d"))
ro = osrmRoute(o, d, sp = T)
```

Great work btw - have you seen our implementation in **stplanr**?

Thinking it could be good to join forces on this, to avoid duplication of effort...

**Comment by rCarto** [comment]
Hi, 
`stplanr` is really nice and has a lot of features. 

I would like to keep osrm as a standalone package. I need it for my work and I need it to be a, relatively, lightweight package. 

Do you think that's a good idea to : 
* submit osrm to rOpenSci
* add the 'nearest' function (and any missing features) to the package
* adapt stplanr to use osrm as a dependency 

I am open to any suggestions.
