### ISSUE TITLE
Multiple distances with osrmRoute?

### ISSUE THREAD

**Issue by Linalalina** [rCarto/osrm#18]
Hello,
I'm a new user of the package and love it so far, thank you!!
I do have a question if I can use osrmRoute to get multiple distances? I have a table of a couple of 100 coordinates from -> to. So a Matrix is out. 
Data structure of a is ID, x, y, Long, lat (with x and y being the source coordinates and Long, lat being the Destination coordinates). The function works perfectly with just one row, but as soon as I ask for 2 rows I get an error message 
> route <- osrmRoute (src = a[1:2, c("id","x","y")],
+                     dst = a[1:2, c("id","long","lat")], overview="simplified", sp="TRUE")
osrmRoute function returns an error: 
Error: URL string malformed close to position 32: "23, 13"

since I only Need the distance(and maybe minutes, but not neccessarily), is there a way get those for multiple lines?
Thank you!
Lina

**Comment by rCarto** [comment]
Hello, 
osrmRoute (based on the route service of OSRM) cannot compute multiple routes in one call. 
You could build a loop that goes through each row of `a` to store each individual routes in a list. 
Or, if you only need the duration (not the distance), you can use the osrmTable function.

**Comment by Linalalina** [comment]
Hi Carto,
thanks, I did program a Loop, had some Problems with the overview Option "simplified" (no method for coercing this S4 class to a vector   ), but with "FALSE" it works! Thanks so much!

**Comment by rCarto** [comment]
To overcome the "no method for coercing this S4 class to a vector" warning I think you should start the `sp` library at the beginning of your script (`library(sp)`).

**Comment by rCarto** [comment]
demo here : https://stat.ethz.ch/pipermail/r-sig-geo/2017-November/026158.html
