### ISSUE TITLE
Implement the google polylines algorythm to have faster osrmViarouteGeom queries

### ISSUE THREAD

**Issue by rCarto** [rCarto/osrm#2]

**Comment by mthh** [comment]
I was about to tell you that I probably could help but I saw this [gist](https://gist.github.com/diegovalle/916889) (with inline c++, as i was wondering about inline C) and I guess there is a neater example in pure R on [stackoverflow] (http://stackoverflow.com/a/32477722/5050917)  (it basicly look like the same procedure as in python, though I did not tested it).
