### ISSUE TITLE
Error with osrmTable

### ISSUE THREAD

**Issue by melaineFR** [rCarto/osrm#23]
Hi,

when i'm using osrmTable I have this error : 
"osrmTable function returns an error: 
Error in function (type, msg, asError = TRUE) : Failed to connect to router.project-osrm.org port 80: Timed out"
Could you help me or explain why ?

Furthermore, I would know if it is still possible to have a road distance matrix between points ? (as the osrmTableOD did)

Thanks

**Comment by rCarto** [comment]
Hello, 
See #22 for the error. 
The purpose of osrmTable is to have a road distance matrix between points. 
cheers
