### ISSUE TITLE
Error on example code

### ISSUE THREAD

**Issue by CharlFM** [rCarto/osrm#24]
When I run the code :
`# Load data`
`data("com")`
`# Travel path between points`
`route <- osrmRoute(src = com[1, c("comm_id", "lon","lat")], `
`                   dst = com[15, c("comm_id", "lon","lat")])`

I get the following error:

`osrmRoute function returns an error: `
`Error: parse error: premature EOF`
`                                       `
`                     (right here) ------^`

I looked around and found that it could be the OSM server - perhaps this is indeed it. You refer to this site: https://github.com/Project-OSRM/osrm-backend/wiki/Building-OSRM

But you don't say how to use it, once I have the repo cloned, then what? How do I "link" R to this?

I am sorry, I am not a full stack coder, this goes beyond my skill level and would really appreciate some help.

Thanks!

**Comment by rCarto** [comment]
Hi, 
Yes, I think the public osrm server is down (see #22). 
To get your own server running OSRM the best place to ask or to get documentation is  on the OSRM repo (https://github.com/Project-OSRM/osrm-backend).
Once you've got your server running you can tell R where to find it with:
```r
options(osrm.server = "http://address.of.the.server/")
```
The default address for a local server should be something like http://0.0.0.0:5000/
