### ISSUE TITLE
Requests for distance & time

### ISSUE THREAD

**Issue by cristianvaldez** [rCarto/osrm#25]
How many requests can be made? I have about 500 points and I would like to check the time and distance between each point, is there a problem if I make the request? It will be about 500*499/2 single requests.

**Comment by rCarto** [comment]
If you don't really need the distances then you can use the `osrmTable` function, a single request would do the job.
If you use the OSRM demo server (which is the default server for the `osrm` package) you should read its [API usage policy](https://github.com/Project-OSRM/osrm-backend/wiki/Api-usage-policy) and decide if your usage can be judged excessive (and 124750 requests is a lot of requests...).
The best solution would be to install your own OSRM server, you wouldn't have any limitations...
