### ISSUE TITLE
The OSRM Demo Server is down

### ISSUE THREAD

**Issue by dorolemke** [rCarto/osrm#27]
Since the OSRM Demo Server is down and the Mapbox API is used as the official OSRM demo instead. It is not clear for me how can I use this API through the osrm-package?

**Comment by rCarto** [comment]
Hello, 
The package is not made to stick to the demo server and should still work with OSRM servers (not the demo one obviously). Anyway, I will try to adapt the package to the Mapbox API.

**Comment by dorolemke** [comment]
Thank you!

**Comment by rCarto** [comment]
It seems that the public demo server is back. The current github version of the package should work with it.
