### ISSUE TITLE
osrmTable/osrmTrip Issue with number of Inputs

### ISSUE THREAD

**Issue by markluxton1** [rCarto/osrm#28]
I'll admit I could be doing something wrong and not realize it, but if so, I am having trouble seeing my mistake.  

I am having the same issue with the osrmTable and osrmTrip functions, but I have no problem with osrmRoute.  For example, I can run this with no issues:
```
route <- osrmRoute(src = center[1, c("cbsa", "Longitude","Latitude")],
                   dst = center[2, c("cbsa", "Longitude","Latitude")])
```
but when I run
`distCom <- osrmTable(loc = center[1:5,c("cbsa","Longitude","Latitude")])`

I get

> osrmTable function returns an error: 
> Error: Not enough input coordinates given; minimum number of coordinates is 2.

and I get the exact same error with osrmTrip.  This doesn't appear to be related to my data since the demo code in the documentation has this same problem:
```
data("com")
# Travel path between points
route <- osrmRoute(src = com[1, c("comm_id", "lon","lat")],
                   dst = com[15, c("comm_id", "lon","lat")])
```
works just fine but I get the same error when I run
```
data("com")
# Travel time matrix
distCom <- osrmTable(loc = com[1:50, c("comm_id","lon","lat")])
```

**Comment by rCarto** [comment]
This problem is due to changes introduced in the osrm demo server (switch from osrm-routed to osrm-routed.js, https://lists.openstreetmap.org/pipermail/osrm-talk/2017-October/001545.html). 
The `osrm` package works fine if you use your own server (https://github.com/Project-OSRM/osrm-backend#using-docker)
