### ISSUE TITLE
url malformed

### ISSUE THREAD

**Issue by F0rth** [rCarto/osrm#29]
I'm trying to use rCarto/osrm with my local osrm server, but the url looks malformed:
OSRM returned an error:
Error: InvalidUrl
URL string malformed close to position 4: "v1/dri"

the osrm log output:
15-12-2017 23:05:02 5.59688ms 172.17.0.1 - 'osrm' R package 400 /v1/driving/

according to https://github.com/Project-OSRM/osrm-backend//docs/http.md
the {service} should come first.

**Comment by rCarto** [comment]
Can you provide a reproducible example please? I don't know what version of OSRM you are using nor what function you are trying to use, and the link to Project-OSRM does not work...

**Comment by F0rth** [comment]
my bad, I'm using osrm-backend 5.14.2, here the correct link to the doc:
https://github.com/Project-OSRM/osrm-backend/blob/5.14/docs/http.md

launching orsm routing daemon on a subset of osm:
[forth@debian osrm]$ ../../osrm-backend-5.14.2/build/osrm-routed -a mld ./rhone-alpes-171206.osrm
[info] starting up engines, v5.14.2
[info] Threads: 4
[info] IP address: 0.0.0.0
[info] IP port: 5000
[info] load names from: "./rhone-alpes-171206.osrm.names"
[info] set checksum: 1297240911
[info] set checksum: 1297240911
[info] set checksum: 1297240911
[info] set checksum: 1297240911
[info] set checksum: 1297240911
[info] set checksum: 1297240911
[info] set checksum: 1297240911
[info] set checksum: 1297240911
[info] http 1.1 compression handled by zlib version 1.2.8
[info] Listening on: 0.0.0.0:5000
[info] running and waiting for requests
[info] 19-12-2017 21:40:11 1.198ms 127.0.0.1 - 'osrm' R package 400 /v1/driving/5.370536,44.751036;NA,NA;5.452401,44.6151;5.370801,44.660123?steps=false&geometries=geojson&overview=simplified
[info] 19-12-2017 21:40:11 0.058843ms 127.0.0.1 - 'osrm' R package 400 /v1/driving/5.370536,44.751036;NA,NA;5.452401,44.6151;5.370801,44.660123
[info] 19-12-2017 21:40:49 0.063741ms 127.0.0.1 - 'osrm' R package 400 /v1/driving/5.724524,45.188529;4.835659,45.764043?steps=false&geometries=geojson&overview=simplified
[info] 19-12-2017 21:40:49 0.089762ms 127.0.0.1 - 'osrm' R package 400 /v1/driving/5.724524,45.188529;4.835659,45.764043

sample R script:
library('ggmap')
library('sp')
library('rgeos')
library('mapview')
library(osrm)
options(osrm.server = "http://127.0.0.1:5000")
library("knitr")

villes <- c("Grenoble, France", "Lyon, France")
parcours <- data.frame(names= villes)
geocodes <- geocode(as.character(villes))
parcours <- data.frame(parcours, geocodes)
trips <- osrmTrip(parcours)
mapview(trips[[1]]$trip)
table <- osrmTable(parcours)
kable(table$durations)

**Comment by rCarto** [comment]
You should end the osrm.server adresse with a "/":
` options(osrm.server = "http://127.0.0.1:5000/")`
