### ISSUE TITLE
osrmViarouteGeom()

### ISSUE THREAD

**Issue by trosendal** [rCarto/osrm#3]
Hi, thanks for the great package!

I'm curious if you know if it is possible to get the route object back with an associated time at each point from 'osrm'. Something like this:

```{r}
library(osrm)
df <- osrmViarouteGeom(17.743773, 59.740056,17.757533, 59.739084)
df$time <- osrmTable(a, id = NULL, x = "lon", y = "lat")[1,]
df
```
Of course the above code works but it seems like the times should already be available from the route calculation and that the calculation of the times is somehow repeating what was already done?

**Comment by rCarto** [comment]
The OSRM API does not provides detailed time data at each node of the route. It can provides intermediates distance at direction points ("turn at bvd Lambda, 200m"). 
The proper way to obtain these times could be something like:
```r
library(osrm)
data("com")
routeGeom <- osrmViarouteGeom(xo = com[1,"lon"], yo = com[1,"lat"],
                              xd = com[15,"lon"], yd = com[15,"lat"])
routeGeom$id <- 1:nrow(routeGeom)
routeGeom$time <- osrmTableOD(dfo = routeGeom[1,], 
                              ido = "id", xo =  "lon", yo =  "lat", 
                              dfd = routeGeom[,], 
                              idd = "id", xd = "lon", yd = "lat")
```
But the longer the route the larger the number of queries sent to the API is.

**Comment by trosendal** [comment]
Thanks,
I'm running the osrm server locally and therefore I can make requests for travel time with vectors longer than 100. It seems that the `system.time()` for the two methods above is quite similar.

Thanks for your help :)
