### ISSUE TITLE
Isometric map

### ISSUE THREAD

**Issue by 4ffectus** [rCarto/osrm#33]
Hey! Is there any possibility of getting an isometric map, with diriving distance rings instead of driving time?

**Comment by rCarto** [comment]
Hello! 
This feature is not implemented yet. I will first have to update osrmTable to extract distance tables.

**Comment by Ilana-R** [comment]
Hello! Has this feature been implemented? I'm new to using GitHub, so apologies if I am not looking in the right place. Thank you!

**Comment by matt439miller** [comment]
Now exists, using osrmIsochrone

**Comment by Ilana-R** [comment]
Amazing! Thank you so much.

________________________________

**Comment by Anyaoha** [comment]
Hello. 
How do I add location along the path of travel so that I can get my route plotted at those points as well.
I'd appreciate a solution to this question. Thanks'

**Comment by rCarto** [comment]
> Hello.
> How do I add location along the path of travel so that I can get my route plotted at those points as well.
> I'd appreciate a solution to this question. Thanks'

See #41

**Comment by martin151190** [comment]
Hi, I run the function:
`iso2 <- osrmIsochrone(loc = c(-60.694696,-32.878606), 
                      breaks = 20,exclude = NULL,
                      res=30
                      )`

But when I plot in a map I saw that not exactly.
![image](https://user-images.githubusercontent.com/30469049/65057900-b724e800-d949-11e9-99cf-c9da629935b6.png)

**_Why the fuction return some polygons thats not include in the principal SpatialPolygonDataframe?._**

Thanks for all.
Martín

**Comment by rCarto** [comment]
see #34

**Comment by rCarto** [comment]
> Hey! Is there any possibility of getting an isometric map, with diriving distance rings instead of driving time?

I do not plan to implement this feature at the moment. If someone want to do it I'm open to PR, I can help to find the relevant parts to adapt in the code.
