### ISSUE TITLE
Multiple polygons created with Isochrone

### ISSUE THREAD

**Issue by yingtaoxie** [rCarto/osrm#34]
Hi,
   I am trying to create some isochrones with the package, but the resulting map always includes more than 1 polygons for a single point. Is there a reason why multiple polygons rather than just one are created? 

   The code I am using looks similar to the package sample:
`iso <- osrmIsochrone(loc = c(36.8032934, -1.2567891), breaks = seq(from = 0, to = 10, by = 10), res = 100)`

![rplot](https://user-images.githubusercontent.com/42247153/46697715-3dd23080-cbe3-11e8-982a-7b3f47ba32e2.png)

**Comment by e-kotov** [comment]
This is probably a side effect of the mechanism for isochrone creation in osrm package: OD matrix sampling, rasterisation, then contour lines are created from the raster... therefore you see these artefacts.

Try playing around with the **res** argument.

Here's an overview of the possible isochrone generation techniques (in Python...). It may be useful for understanding that osrm approach is not the only one out there.
http://kuanbutts.com/2017/12/16/osmnx-isochrones/

**Comment by rCarto** [comment]
thx for the reply @e-kotov
