### ISSUE TITLE
graph-based isochrones / isodistances

### ISSUE THREAD

**Issue by e-kotov** [rCarto/osrm#36]
Hi,

I have been working for awhile with various isochrone generation tools and techniques and tumbled upon this blog post:
http://kuanbutts.com/2017/12/16/osmnx-isochrones/

Do you think it is viable to try doing the isochrone generation in the **osrm** package for R using  the igraph package ( https://github.com/igraph/rigraph ) ? The end result seems very precise and professional. Current isochrone maps produced by osrm and galton ( https://github.com/urbica/galton ) look very nice, but the lie a little bit about the real reachability of places.

**Comment by rCarto** [comment]
Hi, 
I would be happy to use a more precise or elegant way to construct isochrones in osrm. 
The current function (`rasterToContourPoly()`) initially comes from `SpatialPosition` package and is quite convoluted...

If I understand correctly, the method proposed by Kuan Butts is based on an actual network (with nodes and edges). osrm (and the underlying OSRM server) does not allow to output the network but only the distance matrix. I think that make this method unusable?

Anyway, I am open to any suggestion to improve the isochrone construction process...

**Comment by rCarto** [comment]
@e-kotov, I think I can close this issue for now. Don't hesitate to come back if you have any suggestion to improve isochrones creation.
