### ISSUE TITLE
osrmIsochrone incorrect result

### ISSUE THREAD

**Issue by obhakim** [rCarto/osrm#38]
i have for example, loc = c(2.7353, 46.9514), duration = 45, res = 10  gives incorrect result coords 5 points
but when we change de res = 45 we get the correct result between 15 and 20 points

**Comment by rCarto** [comment]
I am not sure I understand your issue here. There is no duration argument in `osrm`. 
Doing :
```r
library(sf)
library(sp)
library(cartography)
library(osrm)
iso45res10 <- osrmIsochrone(loc = c(2.7353, 46.9514), breaks = 45, res = 10)
iso45res45 <- osrmIsochrone(loc = c(2.7353, 46.9514), breaks = 45, res = 45)
osm <- getTiles(x = iso45res45)
par(mar = c(0,0,0,0))
tilesLayer(osm)
plot(iso45res10, lwd = 2, border = "red", add=T)
plot(iso45res45, lwd = 2, border = "blue", add=T)
points(x = 2.7353, y = 46.9514, pch = 20, cex = 2)
```
I have:

![rplot](https://user-images.githubusercontent.com/3041254/49881024-a335de00-fe2d-11e8-9ed4-03548b760af9.png)

which seems correct.

**Comment by obhakim** [comment]
this is the result of another coordination

![2018-12-12_151950](https://user-images.githubusercontent.com/20887664/49882304-9ebef480-fe30-11e8-951d-dfd05cbd2454.jpg)

**Comment by obhakim** [comment]
lat <- 43.756989
lng <- 4.079149 
duration <- 45
iso <- osrmIsochrone(loc = c(lng, lat), breaks = seq(from = 0,to = duration, by = duration))
iso@polygons[[1]]@Polygons[[1]]@coords[, 2:1]


![2018-12-12_185704](https://user-images.githubusercontent.com/20887664/49888663-d719ff00-fe3f-11e8-8dc3-ad3bb99e5c88.jpg)

**Comment by rCarto** [comment]
Sorry, I still do not understand your problem...

Doing:
```r
library(osrm)
library(sp)
library(cartography)
lat <- 43.756989
lng <- 4.079149
duration <- 45
iso <- osrmIsochrone(loc = c(lng, lat), breaks = seq(from = 0,to = duration, by = duration))
osm <- getTiles(iso)
tilesLayer(osm)
points(lng, lat, pch = 20, cex = 2)
plot(iso, add=T)
```
I see:
![image](https://user-images.githubusercontent.com/3041254/49925936-a75c0d00-feba-11e8-8ca4-463e90b8d70e.png)

Which seems OK.
By the way if you want to access coordinates of the polygon, you should use 
```r
iso@polygons[[1]]@Polygons[[1]]@coords[, 2:1]
```
mind the capital "P" of the second Polygon slot...

**Comment by obhakim** [comment]
Thank  you for your response, i tested your code and i got one diff, how can i merge the two plots coordinations as your image example ?

![2018-12-13_113109](https://user-images.githubusercontent.com/20887664/49932952-b480f800-feca-11e8-9451-f65419241f57.jpg)

**Comment by rCarto** [comment]
see #34
