### ISSUE TITLE
osrmRoute get route waypoints

### ISSUE THREAD

**Issue by obhakim** [rCarto/osrm#39]
Hi, there is any method to get the center point of route or to get all  waypoints [lat, lng] of a route ??

![2018-12-18_112304](https://user-images.githubusercontent.com/20887664/50147834-5c296c00-02b7-11e9-8808-e62725c87c89.jpg)

**Comment by rCarto** [comment]
Try `osrmRoute(..., sp=FALSE)` , the output is a data.frame of the waypoints. 
It is in the documentation (`?osrmRoute`) : 
> If sp is FALSE, a data frame is returned. It contains the longitudes and latitudes of the travel path between the two points.
