### ISSUE TITLE
Large requests to local server

### ISSUE THREAD

**Issue by EvanOdell** [rCarto/osrm#4]
The osrmTable() and osrmTableOD() commands to my local server are still limited to 100, even when using the limit function to increase the limit:

    table2 <- osrmTable(distance[1:100,], id = "URN", x = "Long", y = "Lat")
    table3 <- osrmTable(distance[1:101,], id = "URN", x = "Long", y = "Lat")
    osrmTable function returns an error: 
    Error in dimnames(mat) <- list(df[, id], df[, id]): attempt to set an attribute on NULL

With the limit function to increase the limit:

    travel.times <- osrmTableOD(dfo = distance[1:520,], ido = "URN", xo = "Long", yo = "Lat", dfd =     distance[1:520,], idd = "nid", xd = "NLong", yd = "NLat", limit = 3257)
    osrmTable function returns an error: 
    Error in dimnames(mat) <- list(df[, id], df[, id]): attempt to set an attribute on NULL

Is there something else that I need to change to get around this limit?

**Comment by rCarto** [comment]
Have you have started the osrm server with the `--max-table` parameter set to something largeur than 100?

**Comment by EvanOdell** [comment]
I have, the same error keeps happening. Terminal is clearly returning some data, every time I run a command the list of coordinates is displayed in the Terminal window, but in R I'm getting the same error.

**Comment by rCarto** [comment]
I won't have access to my osrm instance till the 4th of January, so I can only try to guess solutions here. 
The list on the terminal means that queries are actually sent to osrm, not that R is receiving a response. 
Which version of osrm server are you running? Some previous versions needed to be modified before build to authorize larger table queries.

**Comment by EvanOdell** [comment]
That is alright, I managed to figure out what was wrong, my commands to change the request limit in OSRM wasn't working. Thanks for your help.

**Comment by rCarto** [comment]
Good to hear that!

**Comment by Anyaoha** [comment]
@evanodell could you share with me how you manage to get this done. I'm running on difficulties in setting the osrm, local server and limits in R studio

**Comment by evanodell** [comment]
@Anyaoha This was my osrm setup:

```
wget http://download.geofabrik.de/europe/great-britain/england-latest.osm.pbf
osrm-extract -p ../profiles/car.lua england-latest.osm.pbf

osrm-extract england-latest.osm.pbf -p profiles/car.lua

./osrm-contract england-latest.osrm
osrm-routed --max-table-size=999999999 england-latest.osrm
```
Or at least that is what I have saved, I haven't looked at that particular project in several years. Hopefully this works for you.

**Comment by Anyaoha** [comment]
Thanks @evanodell thanks.
I have my osrmTable set out with that and I’m currently working above the restrictions of the osrmTable.

My question now is how do I extend the restriction on the osrmRoute in order to work with more route analysis with osrm
