### ISSUE TITLE
osrmRoute with via points

### ISSUE THREAD

**Issue by rCarto** [rCarto/osrm#41]
Hello. 
How do I add location along the path of travel so that I can get my route plotted at those points as well.
I'd appreciate a solution to this question. Thanks'

_Originally posted by @Anyaoha in https://github.com/rCarto/osrm/issues/33#issuecomment-474679242_

**Comment by rCarto** [comment]
This is not possible in `osrm` yet. OSRM server allow to pass several points in the route service.

**Comment by Anyaoha** [comment]
Thanks @rCarto.

I have two questions, and I would appreciate if you can get me answers to the best of your knowledge.

Is it possible to plot road routes which are on osrm using leaflet or mapview?
How do I extend the number of co-ordinates to be routed over 100 points on osrm

**Comment by rCarto** [comment]
1. A simple example to plot routes with `mapview`:
```r
library(osrm)
# Travel path between points between points - output a SpatialLinesDataFrame
route <- osrmRoute(src = c("A", 13.43853, 52.47728),
                   dst = c("B", 13.32247, 52.48882),
                   sp = TRUE, overview = "full")
library(mapview)
mapview(route)
```
Displaying the underlying OSRM road network is not possible. You can have a look at the `osmdata` package. 

2. Getting routes with via points implies modifying the code of the `osrmRoute()` function. I'll have a look into that feature as soon as possible.

**Comment by Anyaoha** [comment]
@rCarto I had plotted the routes of some locations. The maximum number of locations allowed for routing using the OSRM is 100 coordinate points.

Kindly let me know if you get some findings on expanding this restriction.
Thanks

**Comment by Anyaoha** [comment]
@rCarto I had plotted the routes of some locations. The maximum number of locations allowed for routing using the OSRM is 100 coordinate points.

Kindly let me know if you get some findings on expanding this restriction.
Thanks

**Comment by Anyaoha** [comment]
> I don't know how the R studio module works.  If it's making requests to the OSRM demo server at `https://router.project-osrm.org/`, then you'll need to learn how to install and build OSRM separately, then run `osrm-routed` with the option I posted above.

_Originally posted by @danpat in [https://github.com/Project-OSRM/osrm-backend/issues/5421#issuecomment-479123856_](https://github.com/Project-OSRM/osrm-backend/issues/5421#issuecomment-479123856_)

@rCarto What do you think of this?
I think there's a way here. Do you think you can make this happen?

**Comment by rCarto** [comment]
The `osrm` **package** use an `OSRM` **server**. The default server has limitations. You can run your own instance of `OSRM` **server** (via docker) with the described options to get rid of the limitations and make `osrm` **package** use your server.

**Comment by Anyaoha** [comment]
That’s why I reached out to you @rCarto.
How can I get this done using R

**Comment by rCarto** [comment]
As stated in the documentation, to change the OSRM server, change the osrm.server option: 
```r
options(osrm.server = "http://address.of.the.server/")
```

**Comment by Anyaoha** [comment]
Thanks @rCarto I got osrm to work using the local host. I can now use the `osrmTable`for more than 100 coordinate points but I have concerns about `osrmTrip` because I still get errors of `The OSRM server returned an error:
Error: TooBig
Too many trip coordinates` when I try to use in for analysis greater than 100 coordinates. 
I  need help please.

**Comment by rCarto** [comment]
Hmm, there may be an other option to set on the server side. I would search on the OSRM engine documentation.

**Comment by Anyaoha** [comment]
I have set it already. Thanks

For those who would like to get solution from my experience. 
Here's how I got it done. 
`osrm-routed --max-trip-size X map.xml.osrm` where `X` is the size you'd like to use.

**Comment by rCarto** [comment]
version 3.3.2 should address the original question
