### ISSUE TITLE
Travel salesman problem  with OSRM using R

### ISSUE THREAD

**Issue by Anyaoha** [rCarto/osrm#43]
I read about how the OSRM could be used to solve the Traveling Salesman Problem (TSP). [https://medium.com/@janakachathuranga/leaving-google-maps-use-osrm-for-routing-aa1afc912df3](url)

I can not find how this can be implemented in R using the OSRM. I need help with this. Thanks

**Comment by Anyaoha** [comment]
https://medium.com/@janakachathuranga/leaving-google-maps-use-osrm-for-routing-aa1afc912df3

**Comment by rCarto** [comment]
You can use `osrmTrip()`.

**Comment by Anyaoha** [comment]
Thanks @rCarto I had used osrmTrip which actually plots the routes I wasn’t aware it was also solving the TSP

**Comment by Anyaoha** [comment]
My interest was to dynamize my route based on some certain conditions. That’s why I’m on the look out on how to implement dynamic routing.
Let me know if you can help 
Thanks
