### ISSUE TITLE
specific invalid coordinate issue with osrmIsochrone

### ISSUE THREAD

**Issue by jiaweniscute** [rCarto/osrm#44]
Hi There,

Thank you for the awesome package first of all! Really helpful!

I am trying to obtain an area around this particular coordinate in London with the following code:

`test <- osrmIsochrone(loc = c(0.0370781,51.48189), breaks = seq(from = 0,to=8,by=8))
`

I am not sure why but this is giving the following error:

```
The OSRM server returned an error:
Error: InvalidInput
Coordinate is invalid: -9.4e-05,51.407237

The OSRM server returned an error:
Error: InvalidInput
Coordinate is invalid: -9.4e-05,51.458735

The OSRM server returned an error:
Error: InvalidInput
Coordinate is invalid: -9.4e-05,51.510175

Error in UseMethod("st_as_sf") : 
  no applicable method for 'st_as_sf' applied to an object of class "NULL"

```

Any advice would be appreciated!

Thank you so much!

**Comment by rCarto** [comment]
Hello
Mmm, the problem is that `osrm` is sending invalid coordinates to the routing server. 
For this specific point (and I guess any point with coordinates too near to 0, Lat or Long... ) the longitude coordinate is transformed from to its scientific notation (-9.4e-05). 
A quick trick is to set the scipen option to a large value `options(scipen=10)`. 
Thank you for raising this issue, I have to fix this.

**Comment by jiaweniscute** [comment]
Hi there, 

Thank you! This solved the error. 

However, I ran into another problem with this set of coordinates, also in London:   
```
test <- osrmIsochrone(loc = c(-2.4529553,52.71386), 
                           breaks = seq(from = 0,to=8,by=8))
```

For this, the error is: 

```
Error in .as_Spatial(from, cast, IDs) : 
  conversion from feature type sfc_GEOMETRY to sp is not supported
```

Not sure what this means. Would appreciate your help, thank you!!

**Comment by rCarto** [comment]
I'll check this other problem in an other issue (#45).

**Comment by jiaweniscute** [comment]
Apologies, with the update of the package, some of the coordinates are now throwing errors.

For example:

```
test<- osrmIsochrone(loc = c(-0.0435358, 51.49206), 
                      breaks = seq(from = 0,to=8,by=8))
```
The error it is throwing:

```
The OSRM server returned an error:
Error: InvalidInput
Coordinate is invalid: 0.00190 ,51.41742

The OSRM server returned an error:
Error: InvalidInput
Coordinate is invalid: 0.00190 ,51.46891

The OSRM server returned an error:
Error: InvalidInput
Coordinate is invalid: 0.00190 ,51.52034

Error in UseMethod("st_as_sf") : 
  no applicable method for 'st_as_sf' applied to an object of class "NULL"
```

This set of coordinates used to work previously before the update. 

Any idea why this might be so? 

Thank you, again!

**Comment by rCarto** [comment]
Hopefully the last commit has fixed this issue. I'll have a deeper look into it in a few days...
