### ISSUE TITLE
still uncertain if osrm.profile = "walk" in osrmIsochrone works.

### ISSUE THREAD

**Issue by duleise** [rCarto/osrm#50]
hi, similar topic may be discussed before.
To be able to use `osrm.profile = "walk"`, I rebuilt the osrm instance using `foot.lua`. I did this after I finished building the default `car.lua` instance, which worked fine.
However, when I tried to build the instance using `foot.lua` in a totally new environment, I got an error
`[error] Input file "/data/sweden-latest.osrm.ebg" not found!`
I noticed this `.ebg` file was created in the previous step if using `car.lua`, but not `foot.lua`.
So I used `car.lua` first and then `foot.lua` later. It looked like the instance was built okay, and I can set `osrm.profile = "walk"` in `options`. But the results of `osrmIsochrone` was not reassuring. I gave two extreme time intervals to compare.

```
iso <- osrmIsochrone(loc,
                     breaks = seq(from = 0, to = 120, by = 60),
                     res = 400, returnclass = "sf")

```
and the results, according to my eyes, were very much similar, if not identical.
I guess `.ebg` file is where the problem is. Could anybody give some suggestions?
Thanks a lot.

**Comment by rCarto** [comment]
Hello, 
The problem seems related to your OSRM build and not to the R package. I think you should check/post issues here : https://github.com/Project-OSRM/osrm-backend/issues
