### ISSUE TITLE
Allow src and dst to take lon/lat vectors

### ISSUE THREAD

**Issue by Robinlovelace** [rCarto/osrm#51]
Great package, very impressed, planning to use this as a backend in stplanr. One thing that would help that is if `src` and `dst` could take vectors, not just spatial object. Demo of what I mean below. cc @richardellison who may be up for helping with this:

``` r
library(osrm)
#> Data: (c) OpenStreetMap contributors, ODbL 1.0 - http://www.openstreetmap.org/copyright
#> Routing: OSRM - http://project-osrm.org/
    library(stplanr)
#> Registered S3 method overwritten by 'R.oo':
#>   method        from       
#>   throw.default R.methodsS3
    options(osrm.server = "http://0.0.0.0:5000/", osrm.profile = "driving")
    
    l = pct::wight_lines_30
    p = line2points(l)
    r = osrm::osrmRoute(src = p[1, ], dst = p[2, ], returnclass = "sf")
    plot(r)
```

![](https://i.imgur.com/1vH6I8l.png)

``` r
    
    
    route_osrm2 = function(l) {
        p = line2points(l)
        s = (1:nrow(l)) * 2 - 1
        list_out = lapply(s, function(i) osrm::osrmRoute(p[i, ], dst = p[i + 1, ], returnclass = "sf"))
        do.call(rbind, list_out)
    }
    routes_osrm = route_osrm2(l)
    plot(routes_osrm)
```

![](https://i.imgur.com/WLgkamo.png)

``` r
    
    # with coordinates
    c1 = as.numeric(sf::st_coordinates(p[1, ]))
    c2 = as.numeric(sf::st_coordinates(p[2, ]))
    osrm::osrmRoute(src = c1, dst = c2, returnclass = "sf")
#> The OSRM server returned an error:
#> Error: InvalidQuery
#> Query string malformed close to position 27
#> NULL
```

<sup>Created on 2019-09-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rCarto** [comment]
Hello Robin, 
In fact `src` and `dst` can take vectors, but they expect a vector with an identifier and coordinates (something like `c("ID",  "13.41", "52.50")`). I felt it was useful to keep track of the source and destination identifiers when using routes created with `osrmRoute()`. 

``` r
library(osrm)
#> Data: (c) OpenStreetMap contributors, ODbL 1.0 - http://www.openstreetmap.org/copyright
#> Routing: OSRM - http://project-osrm.org/
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.4.0, PROJ 5.2.0
options(osrm.server = "http://0.0.0.0:5000/", osrm.profile = "driving")

route <- osrmRoute(src = c("A", 13.41299, 52.5029), 
                   dst = c("B", 13.45456, 52.59265), 
                   returnclass = "sf")
plot(route)
```

![](https://i.imgur.com/wkAmFhN.png)

``` r
data("berlin")
s <- c(1:44,46:100)
list_out <- lapply(s, function(i){osrmRoute(src = apotheke.df[45,], dst = apotheke.df[i, ], returnclass = "sf")})
routes_osrm <- do.call(rbind, list_out)
routes_osrm <- routes_osrm[order(-routes_osrm$duration),]
plot(routes_osrm["duration"])
```

![](https://i.imgur.com/HDaWn0G.png)

<sup>Created on 2019-09-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


If needed I can add a special case when no identifiers are given (`length(src) == 2`) and use a default id (something like "src").

**Comment by Robinlovelace** [comment]
> If needed I can add a special case when no identifiers are given (length(src) == 2) and use a default id (something like "src").

I think that would be a good solution and reduce the requirement input data. I understand why it was failing now, and understand why keeping the id could be important. Many thanks for quick reply!

**Comment by rCarto** [comment]
@Robinlovelace 
The last few commits should allow lon/lat vectors as input for `osrmRoute()`. 
I have also added a `loc` arg to allow the computation of routes with via points.
Don't hesitate to tell me if other changes could ease the use of the package.

**Comment by rCarto** [comment]
`overview="full"` will give you what you need. `overview=FALSE` will return only a vector of time and distance.  
https://github.com/ropensci/stplanr/issues/340 and https://github.com/ropensci/stplanr/issues/338 seem fine to me.

**Comment by Robinlovelace** [comment]
Many thanks! Experimenting with local routing on `sfNetwork` objects at the moment but I guess OSRM is better for most real-world situations. Looking forward to using it to help build an evidence base for a more sustainable world!
