### ISSUE TITLE
Error: InvalidQuery Query string malformed close to position 6249

### ISSUE THREAD

**Issue by Christoph999** [rCarto/osrm#52]
After an update from 
```
sessionInfo("osrm")$otherPkgs
$`osrm`
Version: 3.1.1
Date: 2018-03-12

```
to 
```
$`osrm`
Version: 3.3.2

```
we receive the following error:
Data: (c) OpenStreetMap contributors, ODbL 1.0 - http://www.openstreetmap.org/copyright
Routing: OSRM - http://project-osrm.org/
Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3
The OSRM server returned an error:
Error: InvalidQuery
Query string malformed close to position 6249

Do you have any idea? Our call (as before the update) is of the type
`osrm::osrmIsochrone(c(lngs[i], lats[i]), breaks, res)`
The same code runs through without any error.

Please let me know, if you need anything else. Thanks a lot!

**Comment by rCarto** [comment]
Hello, 
Thank you for raising this issue. 
I would like to know if you use your own OSRM server. And it would help me a lot to have the values contained in lngs, lats, breaks and res.

**Comment by rCarto** [comment]
Hello, 
Thank you for raising this issue. 
Are you using your own OSRM server ? With the driving profile? 
Also, it would be helpful to have the values of i, lngs, lats, breaks and res.

**Comment by Christoph999** [comment]
Hi, Thanks for your reply. Don't hestite to conatct me, in case you need further details:

the data (from RStudio)
structure(list(PLZ = NA, Stadt = "Erstfeld", Breite = 46.81236378, 
    Laenge = 8.599465297), class = "data.frame", row.names = c(NA, 
-1L))

The relevant code sequence:
library(osrm)
library(sf)

```
res_isochrones <- 50
breaks_isochrones <- seq(90, 120, 30)
path <- paste0(getwd(), "/rawdata/")
map_name = "switzerland-latest"
osrm_path = "C:/OSRM_API5"
filename <- paste0(path, "LagerErstfeld.csv")
datenLager <- read.csv(filename, sep = ";", stringsAsFactors = FALSE)
r <- calculate_isochones(names = datenLager$PLZ, lats = datenLager$Breite[1], 
                         lngs = datenLager$Laenge[1],
                         breaks = breaks_isochrones, 
                         res = res_isochrones, 
                         map_name = map_name,
                         osrm_path = osrm_path) 
```

We use R and a local version of OSRM running on Windows (API5).
The API seems find and I figured out, that in your function, everything seems to be ok until `req <- tableLoc(loc = loc, gepaf = gepaf)` in `osrmTable()`.

**Comment by rCarto** [comment]
Ok I see it. 
Since v3.2.0, a new parameter has been added  in `osrmIsochrone()` (`exclude`, between `breaks` and `res`) . 
I you use explicitly named argument the function should work. Something like : 
```r 
osrm::osrmIsochrone(loc = c(lngs[i], lats[i]), breaks = breaks, res = res)
```
Sorry for the breaking change, I should have added the new param at the end of the list...

**Comment by Christoph999** [comment]
Still the same issue in

```
isochrone_list[[i]] <- osrm::osrmIsochrone(loc = c(lngs[i], lats[i]),
                                           breaks = breaks, res = res)

```
results in 

```
The OSRM server returned an error:
Error: InvalidQuery
Query string malformed close to position 6309

8x the same message...

Error in UseMethod("st_as_sf") : 
  no applicable method for 'st_as_sf' applied to an object of class "NULL"
```

**Comment by Christoph999** [comment]
Hi, it seems, this was not the solution. Can you reproduce the behaviour with my data?
See my comment at Github…

Von: Timothée Giraud <notifications@github.com>
Gesendet: Donnerstag, 3. Oktober 2019 15:04
An: rCarto/osrm <osrm@noreply.github.com>
Cc: Christoph Strauss <christoph.strauss@fhsg.ch>; Author <author@noreply.github.com>
Betreff: Re: [rCarto/osrm] Error: InvalidQuery Query string malformed close to position 6249 (#52)


Ok I see it.
Since v3.2.0, a new parameter has been added in osrmIsochrone() (exclude, between breaks and res) .
I you use explicitly named argument the function should work. Something like :

osrm::osrmIsochrone(loc = c(lngs[i], lats[i]), breaks = breaks, res = res)

Sorry for the breaking change, I should have added the new param at the end of the list...

**Comment by rCarto** [comment]
Using the demo server and the coordinates you sent me I get:
``` r
library(osrm)
#> Data: (c) OpenStreetMap contributors, ODbL 1.0 - http://www.openstreetmap.org/copyright
#> Routing: OSRM - http://project-osrm.org/
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.4.0, PROJ 5.2.0
res <- 50
breaks <- seq(90, 120, 30)
loc <- c(8.599465297, 46.81236378)
iso <- osrmIsochrone(loc = loc, breaks = breaks, 
                     res = res, returnclass = "sf")
plot(st_geometry(iso), col = c("lightblue1", "lightblue3"))
points(loc[1], loc[2], pch = 20, col = "red")
```

![](https://i.imgur.com/UEK90rj.png)

<sup>Created on 2019-10-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


But I don't know what's in the "LagerErstfeld.csv" file...

**Comment by Christoph999** [comment]
Ok, so it is definitely related to the local OSRM:

```
library(osrm)
Data: (c) OpenStreetMap contributors, ODbL 1.0 - http://www.openstreetmap.org/copyright
Routing: OSRM - http://project-osrm.org/
library(sf)
Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3
res <- 50
breaks <- seq(90, 120, 30)
loc <- c(8.599465297, 46.81236378)
iso <- osrmIsochrone(loc = loc, breaks = breaks, 
                     res = res, returnclass = "sf")
plot(st_geometry(iso), col = c("lightblue1", "lightblue3"))
points(loc[1], loc[2], pch = 20, col = "red")
map_name = "switzerland-latest"
osrm_path = "C:/OSRM_API5"
options(osrm.server = paste0(osrmr:::server_address(TRUE), "/"), osrm.profile = "driving")
osrmr::run_server(paste0(map_name, ".osrm"), osrm_path)
res <- 50
breaks <- seq(90, 120, 30)
loc <- c(8.599465297, 46.81236378)
iso <- osrmIsochrone(loc = loc, breaks = breaks, 
                     res = res, returnclass = "sf")
# The OSRM server returned an error:
# Error: InvalidQuery
# Query string malformed close to position 6285
...
Error in UseMethod("st_as_sf") : 
  no applicable method for 'st_as_sf' applied to an object of class "NULL"
```

From our local API (Which is working):
```
C:\OSRM_API5>osrm-routed switzerland-latest
[info] starting up engines, v5.10.0[0m
[info] Threads: 8[0m
[info] IP address: 0.0.0.0[0m
[info] IP port: 5000[0m
[info] load names from: "switzerland-latest.osrm.names"[0m
[info] set checksum: 384967193[0m
[info] http 1.1 compression handled by zlib version 1.2.8[0m
[info] Listening on: 0.0.0.0:5000[0m
[info] running and waiting for requests[0m
```

I hope that helps! I already checked, whether the OSRM API interfaced changed since 5.10, but I couldn't find anything.

**Comment by Christoph999** [comment]
Thanks again for your great support! I understand and I consider this issue as solved.

**Comment by rCarto** [comment]
All right
