### ISSUE TITLE
Using "distance" measure is not possible in osrmIsochrone()

### ISSUE THREAD

**Issue by pasipasi123** [rCarto/osrm#54]
Hi,

I'm running my own OSRM server.

I'd like to get travel _distance_ isochrones from `osrmIsochrone()`. Looking at the code I see that osrmTable has a `measure` argument, but `osrmIsochrone()` has a lot of hard coded variable names for the `"duration"` run, and most likely a variety of other hard coded duration based features.

Would it be possible to add "distance" to `osrmIsochrone()`? If it's a matter of rewriting some parts of the function, I can offer my help. I did try the rewrite some parts to allow for "distance", but I didn't get it to work.

**Comment by rCarto** [comment]
Hi, 
You are right this operation is not possible at the moment (see #33). I'll see what I can do, but to be honest this is not a priority for now. I would be happy to consider a PR if you manage to make it work.

**Comment by pasipasi123** [comment]
I did get it to work. Here: https://github.com/rCarto/osrm/pull/55

**Comment by rCarto** [comment]
fix by #55
