### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by gefero** [rCarto/osrm#56]
Cannot install package on Ubunutu 18

> install.packages('osrm', dependencies=TRUE)
Installing package into ‘/home/grosati/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/osrm_3.3.2.tar.gz'
Content type 'application/x-gzip' length 24411 bytes (23 KB)
==================================================
downloaded 23 KB

* installing *source* package ‘osrm’ ...
** package ‘osrm’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
double free or corruption (out)
Aborted (core dumped)
ERROR: lazy loading failed for package ‘osrm’
* removing ‘/home/grosati/R/x86_64-pc-linux-gnu-library/3.6/osrm’
Warning in install.packages :
  installation of package ‘osrm’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmp4cvRTD/downloaded_packages’

`> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=es_AR.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=es_AR.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=es_AR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=es_AR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.3 tools_3.6.3   `

**Comment by rCarto** [comment]
Hello, 
That's the first time I see this problem. 
Can you post the output of your `sessionInfo()`?

**Comment by gefero** [comment]
So do I...
I have updated the comment...
Sorry I forgot the `sessionInfo()`

**Comment by rCarto** [comment]
Do you have `sp` and `sf` already installed?

**Comment by gefero** [comment]
Yep...

**Comment by rCarto** [comment]
Could you try to install the dev version of the package ? 
`remotes::install_github("rCarto/osrm")`

**Comment by gefero** [comment]
Same problem...

Downloading GitHub repo rCarto/osrm@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

 1: All                                 
 2: CRAN packages only                  
 3: None                                
 4: sp         (1.3-2  -> 1.4-1 ) [CRAN]
 5: sf         (0.8-1  -> 0.9-0 ) [CRAN]
 6: Rcpp       (1.0.3  -> 1.0.4 ) [CRAN]
 7: units      (0.6-5  -> 0.6-6 ) [CRAN]
 8: cli        (2.0.1  -> 2.0.2 ) [CRAN]
 9: digest     (0.6.23 -> 0.6.25) [CRAN]
10: rlang      (0.4.4  -> 0.4.5 ) [CRAN]
11: glue       (1.3.1  -> 1.3.2 ) [CRAN]
12: rstudioapi (0.10   -> 0.11  ) [CRAN]
13: callr      (3.4.1  -> 3.4.3 ) [CRAN]
14: processx   (3.4.1  -> 3.4.2 ) [CRAN]
15: ps         (1.3.0  -> 1.3.2 ) [CRAN]
16: testthat   (2.3.1  -> 2.3.2 ) [CRAN]

Enter one or more numbers, or an empty line to skip updates:

✓  checking for file ‘/tmp/RtmpMJXvNz/remotes10351e540627/rCarto-osrm-ab24106/DESCRIPTION’ ...
─  preparing ‘osrm’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘osrm_3.3.2.tar.gz’
   
Installing package into ‘/home/grosati/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package ‘osrm’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
double free or corruption (out)
Aborted (core dumped)
ERROR: lazy loading failed for package ‘osrm’
* removing ‘/home/grosati/R/x86_64-pc-linux-gnu-library/3.6/osrm’
Error: Failed to install 'osrm' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpMJXvNz/file1035757c8e84/osrm_3.3.2.tar.gz’ had non-zero exit status

**Comment by rCarto** [comment]
Just in case, I would update all packages.

**Comment by gefero** [comment]
That worked!
Thanks!
