### ISSUE TITLE
Recent Increase In Run Time for osrmIsochrone

### ISSUE THREAD

**Issue by ept2020** [rCarto/osrm#59]
I've got a script that I wrote last year which generates a series of isochrones for a fairly small (n<500)  data set. Previously it ran rather quickly, in under 10 minutes. Recently, after updating some packages, it seems to have become much slower, taking roughly 30 seconds for each coordinate pair, several hours for the whole thing. I tried updating R and all required packages to the most recent version on a secondary machine and the runtime is still long, roughly 30 seconds for each pair of coordinates. 

I am thinking a change in a dependency might be the root cause but was wondering if anyone else has noticed this behavior. I do not think that the OSRM server is the issue. I am using a private OSRM instance that has over 100GB of RAM available. North America is the only dataset loaded, I am not running the full planet file. I've rebooted the server and restarted osrm-routed, and test calls that I've made from the Ubuntu command line are successful almost instantaneously. osrmTable when called from R using the latest version of the osrm package is also very fast. Wondering if this might be some sort of issue involving sf and osrmIsochrone.

**Comment by rCarto** [comment]
Hello, 
Thanks for reporting this issue. 
Indeed `osrmIsochrone()` is very slow, this is due to a dumb use of an sf function. My last commit to master should solve this issue. 
Can you please test the dev version (`remotes::install_github('rCarto/osrm')` and report if there is an improvement?

**Comment by ept2020** [comment]
Big improvement using the dev version. A call to osrmIsochrone() using one pair of coordinates is now taking about 1.75 seconds, versus roughly 30 on the most recent version of `osrm` on CRAN. 

Re: previous performance, I think that I recently upgraded `sf`, perhaps something changed with that package that exacerbated the problem that you just fixed? Although I can say that the performance I am getting with the dev version of `osrm` today is roughly equivalent to what I was getting using the CRAN version(probably an older one too) a month or so ago.

**Comment by rCarto** [comment]
Thank you for your feedback. I'll release an updated version as soon as possible.
