### ISSUE TITLE
Error as "lexical error: invalid char in json text"

### ISSUE THREAD

**Issue by danishpazz** [rCarto/osrm#63]
I have been using osrm for a while and haven't come across this issue before. I tried to generate simple 10 minutes isochrone in r. 
`library(sf)
data("berlin")
iso <- osrmIsochrone(loc = c(13.43,52.47), seq(from = 0, to = 30, by = 5),
                     returnclass="sf")`

Error: 
![image](https://user-images.githubusercontent.com/13514742/90342776-72597380-e028-11ea-8f6b-fb66bd5721d2.png)

I tried a lot to resolve and even uninstalled and reinstalled r completely, but no luck at all. Can some, please guide me where am I doing wrong. 

Thanks in advance!!!

@rCarto

**Comment by rCarto** [comment]
Have you tried the dev version of osrm?
