### ISSUE TITLE
`st_make_valid` not found

### ISSUE THREAD

**Issue by barryrowlingson** [rCarto/osrm#64]
Chasing up the gis stackexchange question: https://gis.stackexchange.com/questions/371577/issue-with-osrmisochrone-fucntion-in-r#comment607246_371577

Found your issue #63 

Tried the latest master via `devtools::install_github`:

got:

Error in st_make_valid(st_geometry(iso)) : 
  could not find function "st_make_valid"

I have `st_make_valid` in the `lwgeom` package, so pulling that in via `library(lwgeom)` fixes that. Seems to only be in `Suggests` for the current `master` version of `osrm`:

```
> packageDescription("osrm")
Package: osrm
Type: Package
Title: Interface Between R and the OpenStreetMap-Based Routing Service
        OSRM
Version: 3.3.4.0
Depends: R (>= 3.3.0)
Suggests: cartography, lwgeom
URL: https://github.com/rCarto/osrm
```

Not sure if `st_make_valid` is something that has crept into `sf` in a later version. I have:
```

> packageDescription("sf")
Package: sf
Version: 0.8-1
> packageDescription("lwgeom")
Package: lwgeom
Version: 0.2-1

```

**Comment by rCarto** [comment]
That's it. Depending on the GEOS install, st_make_valid is in 

https://r-spatial.github.io/sf/news/index.html
