### ISSUE TITLE
Does osrmRoute define shortest by time or distance?

### ISSUE THREAD

**Issue by tra6sdc** [rCarto/osrm#65]
Hello, this is not an issue but a question. 

The documentation says that `osrmRoute()` returns the shortest path between two points. Is this the shortest path by travel time or by distance? In inclined to say by distance since if it was time it would say "quickest path".

**Comment by rCarto** [comment]
Hello, 
It is in fact the shortest path by travel time, I may change the documentation to "quickest path" then.

**Comment by sriramab** [comment]
is it possible to specify "time" or "distance" as a parameter?
