### ISSUE TITLE
Change demo server

### ISSUE THREAD

**Issue by rCarto** [rCarto/osrm#67]
Change the demo server for https://routing.openstreetmap.de as it allows to request foot/bike/car routes/tables/trips. 

This version use hacks to allow different profiles (Used profiles section in https://routing.openstreetmap.de/about.html)
- It implies to adapt the package code to accommodate both profile selection for demo server (via  routed-foot/routed-car/routed-bike URL prefixes) and local server (via driving/walk/bike URL prefixes). 
IMO demo server related changes should be invisible to users and profile selection should still pass through options(osrm.profile="walk/bike/driving"). But maybe we should think about another solution to use `osrm` functions without loading the package (`stplanr` use-case I think @Robinlovelace ?).
- Update documentation accordingly (link to https://routing.openstreetmap.de/about.html, explicit recommendation about API usage). In readme and package documentation.

**Comment by Robinlovelace** [comment]
I can have a go at putting in a PR if that would be useful @rCarto.

**Comment by rCarto** [comment]
Yes, sure!

**Comment by Robinlovelace** [comment]
First attempt: see commit above!

**Comment by rCarto** [comment]
Thank you, I'll have a look at it asap. I'll try to drop a new release next week.
