### ISSUE TITLE
Google polyline decoding

### ISSUE THREAD

**Issue by RCura** [rCarto/osrm#9]
I just saw this project, you might want to take a look: [polyline-to-geojson](https://github.com/barryrowlingson/polyline-to-geojson)

Especially considering @barryrowlingson wrote a lot of R packages, he might try to develop a custom package for this decoding task, and you could work with him on this.

**Comment by barryrowlingson** [comment]
All I did was take some JS that did the conversion from a mapbox project, some JS to do upload-convert-link to download from another project, and glue the two together!

The polyline format looks pretty simple, there's python and JS decoders/encoders out there...

**Comment by rCarto** [comment]
`gepaf` package (https://github.com/mthh/gepaf) convert from polyline to data.frame and from data.frame to polyline. It would not be too difficult to use a wrapper to use geosjson format.
I'm not sure if this wrapper should be in gepaf.
@mthh
